version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: "${DB_USER:-bioverse_admin}"
      POSTGRES_PASSWORD: "${DB_PASSWORD:-}"
      POSTGRES_DB: "${DB_NAME:-bioverse_zambia_db}"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  server:
    build: ./server
    environment:
      NODE_ENV: "development"
      PORT: "3000"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_USER: "${DB_USER:-bioverse_admin}"
      DB_PASSWORD: "${DB_PASSWORD:-}"
      DB_NAME: "${DB_NAME:-bioverse_zambia_db}"
      ENABLE_REQUEST_LOGGING: "true"
      ENABLE_RATE_LIMITING: "false"
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
    volumes:
      - ./server:/usr/src/app

  client:
    build: ./client
    ports:
      - '5173:80'
    depends_on:
      - server
    volumes:
      - ./client:/app

volumes:
  pgdata:
    driver: local
