// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8WBbFUvXKN9LJ-7wNYlJhWF0QvF8X9R0',
    appId: '1:1071067852182:web:placeholder',
    messagingSenderId: '1071067852182',
    projectId: 'bioverse-ai',
    authDomain: 'bioverse-ai.firebaseapp.com',
    storageBucket: 'bioverse-ai.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA89rl_1O4-B1R8FEDWeF7jT-hFmKs1QLM',
    appId: '1:1071067852182:android:534bf1584ebf287a3dc1b7',
    messagingSenderId: '1071067852182',
    projectId: 'bioverse-ai',
    authDomain: 'bioverse-ai.firebaseapp.com',
    storageBucket: 'bioverse-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8WBbFUvXKN9LJ-7wNYlJhWF0QvF8X9R0',
    appId: '1:1071067852182:ios:placeholder',
    messagingSenderId: '1071067852182',
    projectId: 'bioverse-ai',
    authDomain: 'bioverse-ai.firebaseapp.com',
    storageBucket: 'bioverse-ai.appspot.com',
    iosBundleId: 'com.bioverse.bioverseMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8WBbFUvXKN9LJ-7wNYlJhWF0QvF8X9R0',
    appId: '1:1071067852182:macos:placeholder',
    messagingSenderId: '1071067852182',
    projectId: 'bioverse-ai',
    authDomain: 'bioverse-ai.firebaseapp.com',
    storageBucket: 'bioverse-ai.appspot.com',
    iosBundleId: 'com.bioverse.bioverseMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8WBbFUvXKN9LJ-7wNYlJhWF0QvF8X9R0',
    appId: '1:1071067852182:web:placeholder',
    messagingSenderId: '1071067852182',
    projectId: 'bioverse-ai',
    authDomain: 'bioverse-ai.firebaseapp.com',
    storageBucket: 'bioverse-ai.appspot.com',
  );
}
