-- BioVerse Coordination Engine Schema
-- Creates all tables needed for DHIS2 integration and stock coordination

-- Facilities table: maps to DHIS2 organisation units
CREATE TABLE IF NOT EXISTS facilities (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL DEFAULT 'PUBLIC_HOSPITAL',
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    dhis2_org_unit_id VARCHAR(50),
    district VARCHAR(255),
    province VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(dhis2_org_unit_id)
);

CREATE INDEX IF NOT EXISTS idx_facilities_dhis2 ON facilities(dhis2_org_unit_id);
CREATE INDEX IF NOT EXISTS idx_facilities_district ON facilities(district);

-- Inventory catalog: maps to DHIS2 data elements
CREATE TABLE IF NOT EXISTS inventory_catalog (
    id SERIAL PRIMARY KEY,
    item_name VARCHAR(255) NOT NULL,
    category VARCHAR(50) NOT NULL DEFAULT 'MEDICATION',
    dhis2_data_element_id VARCHAR(50),
    unit_of_measure VARCHAR(50) DEFAULT 'units',
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(dhis2_data_element_id)
);

CREATE INDEX IF NOT EXISTS idx_inventory_dhis2 ON inventory_catalog(dhis2_data_element_id);

-- Facility stock levels: core coordination data
CREATE TABLE IF NOT EXISTS facility_stock_levels (
    id SERIAL PRIMARY KEY,
    facility_id INTEGER NOT NULL REFERENCES facilities(id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES inventory_catalog(id) ON DELETE CASCADE,
    current_stock INTEGER NOT NULL DEFAULT 0,
    daily_burn_rate NUMERIC(10,2) DEFAULT 0,
    status VARCHAR(20) DEFAULT 'HEALTHY' CHECK (status IN ('CRITICAL', 'HEALTHY', 'SURPLUS')),
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(facility_id, item_id)
);

CREATE INDEX IF NOT EXISTS idx_stock_facility ON facility_stock_levels(facility_id);
CREATE INDEX IF NOT EXISTS idx_stock_status ON facility_stock_levels(status);

-- Transfer alerts: generated by coordination engine
CREATE SEQUENCE IF NOT EXISTS transfer_alerts_id_seq;

CREATE TABLE IF NOT EXISTS transfer_alerts (
    id SERIAL PRIMARY KEY,
    alert_id VARCHAR(50) UNIQUE NOT NULL,
    item_id INTEGER NOT NULL REFERENCES inventory_catalog(id),
    from_facility_id INTEGER NOT NULL REFERENCES facilities(id),
    to_facility_id INTEGER NOT NULL REFERENCES facilities(id),
    surplus_amount INTEGER,
    distance_km NUMERIC(10,2),
    shortage_timeframe VARCHAR(100),
    status VARCHAR(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'CANCELLED')),
    notes TEXT,
    acknowledged_at TIMESTAMPTZ,
    resolved_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_alerts_status ON transfer_alerts(status);

-- DHIS2 sync log: tracks ingestion history
CREATE TABLE IF NOT EXISTS dhis2_sync_log (
    id SERIAL PRIMARY KEY,
    sync_type VARCHAR(50) NOT NULL,
    status VARCHAR(20) DEFAULT 'RUNNING',
    records_processed INTEGER DEFAULT 0,
    records_failed INTEGER DEFAULT 0,
    error_message TEXT,
    started_at TIMESTAMPTZ DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

-- DHIS2 org unit mapping: caches org unit metadata from DHIS2
CREATE TABLE IF NOT EXISTS dhis2_org_unit_map (
    id SERIAL PRIMARY KEY,
    dhis2_uid VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    level INTEGER,
    parent_uid VARCHAR(50),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    facility_id INTEGER REFERENCES facilities(id),
    last_synced TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_org_unit_map_uid ON dhis2_org_unit_map(dhis2_uid);

-- DHIS2 data element mapping: caches data element metadata from DHIS2
CREATE TABLE IF NOT EXISTS dhis2_data_element_map (
    id SERIAL PRIMARY KEY,
    dhis2_uid VARCHAR(50) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    short_name VARCHAR(100),
    value_type VARCHAR(50),
    item_id INTEGER REFERENCES inventory_catalog(id),
    last_synced TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_data_element_map_uid ON dhis2_data_element_map(dhis2_uid);
